using Avalonia.Controls;
using DataVisualizationApp.ViewModels;

namespace DataVisualizationApp.Views
{
    public partial class Nr3PieChartView : UserControl
    {
        public Nr3PieChartView()
        {
            InitializeComponent(); // This method is generated by the XAML build process
            DataContext = new Nr3PieChartViewModel();
        }
    }
}
